service: epm_registry
image: ghcr.io/nickagliano/epm_registry

servers:
  web:
    - 178.156.215.141

proxy:
  app_port: 80
  # ssl: true
  # host: yourdomain.com   # uncomment when domain is ready

registry:
  server: ghcr.io
  username: nickagliano
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "epm_registry_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16
    host: 178.156.215.141
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: epm_registry
        POSTGRES_DB: epm_registry_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
